name: Hprofile Actions
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs: 
  Testing:
    runs-on: ubuntu-latest
    steps: 
      - name: Code Checkout
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      
      - name: Maven test
        run:  mvn test
      
      - name: checkstyle
        run: mvn checksytle:checkstyle

        

